### ISSUE TITLE
Uncaught Error: This TextEditor has been destroyed

### ISSUE THREAD

**Issue by Rdbllx** [T-800/REPL-Nodejs#6]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.0.15
**System**: Unknown Windows Version
**Thrown From**: [Repl](https://github.com/T-800/REPL-Nodejs) package, v0.5.0

### Stack Trace

Uncaught Error: This TextEditor has been destroyed

```
At C:\Users\raph\AppData\Local\atom\app-1.0.15\resources\app.asar\node_modules\text-buffer\lib\text-buffer.js:770

Error: This TextEditor has been destroyed
  at DisplayBuffer.module.exports.DisplayBuffer.screenPositionForBufferPosition (C:\Users\raph\AppData\Local\atom\app-1.0.15\resources\app.asar\src\display-buffer.js:1097:15)
  at Marker.module.exports.Marker.getHeadScreenPosition (C:\Users\raph\AppData\Local\atom\app-1.0.15\resources\app.asar\src\marker.js:179:33)
  at Cursor.module.exports.Cursor.getScreenPosition (C:\Users\raph\AppData\Local\atom\app-1.0.15\resources\app.asar\src\cursor.js:90:26)
  at Cursor.module.exports.Cursor.getScreenRange (C:\Users\raph\AppData\Local\atom\app-1.0.15\resources\app.asar\src\cursor.js:708:20)
  at Cursor.module.exports.Cursor.autoscroll (C:\Users\raph\AppData\Local\atom\app-1.0.15\resources\app.asar\src\cursor.js:713:51)
  at Selection.module.exports.Selection.autoscroll (C:\Users\raph\AppData\Local\atom\app-1.0.15\resources\app.asar\src\selection.js:955:28)
  at Selection.module.exports.Selection.clear (C:\Users\raph\AppData\Local\atom\app-1.0.15\resources\app.asar\src\selection.js:198:14)
  at Selection.module.exports.Selection.insertText (C:\Users\raph\AppData\Local\atom\app-1.0.15\resources\app.asar\src\selection.js:456:12)
  at C:\Users\raph\AppData\Local\atom\app-1.0.15\resources\app.asar\src\text-editor.js:745:29
  at C:\Users\raph\AppData\Local\atom\app-1.0.15\resources\app.asar\src\text-editor.js:787:29
  at TextBuffer.module.exports.TextBuffer.transact (C:\Users\raph\AppData\Local\atom\app-1.0.15\resources\app.asar\node_modules\text-buffer\lib\text-buffer.js:765:18)
  at TextEditor.module.exports.TextEditor.transact (C:\Users\raph\AppData\Local\atom\app-1.0.15\resources\app.asar\src\text-editor.js:1168:26)
  at C:\Users\raph\AppData\Local\atom\app-1.0.15\resources\app.asar\src\text-editor.js:781:24
  at TextEditor.module.exports.TextEditor.mergeSelections (C:\Users\raph\AppData\Local\atom\app-1.0.15\resources\app.asar\src\text-editor.js:2037:18)
  at TextEditor.module.exports.TextEditor.mergeIntersectingSelections (C:\Users\raph\AppData\Local\atom\app-1.0.15\resources\app.asar\src\text-editor.js:1999:35)
  at TextEditor.module.exports.TextEditor.mutateSelectedText (C:\Users\raph\AppData\Local\atom\app-1.0.15\resources\app.asar\src\text-editor.js:779:19)
  at TextEditor.module.exports.TextEditor.insertText (C:\Users\raph\AppData\Local\atom\app-1.0.15\resources\app.asar\src\text-editor.js:742:19)
  at TextEditor.object.(anonymous function) [as insertText] (C:\Users\raph\AppData\Local\atom\app-1.0.15\resources\app.asar\node_modules\underscore-plus\lib\underscore-plus.js:77:27)
  at REPLView.module.exports.REPLView.dealWithRetour (C:\Users\raph\.atom\packages\Repl\lib\Repl-View\ReplView.coffee:91:23)
  at Repl.retour (C:\Users\raph\.atom\packages\Repl\lib\Repl-View\ReplView.coffee:1:1)
  at Repl.module.exports.Repl.processOutputData (C:\Users\raph\.atom\packages\Repl\lib\Repl\ReplClass.coffee:48:8)
  at Socket.<anonymous> (C:\Users\raph\.atom\packages\Repl\lib\Repl\ReplClass.coffee:96:51)
  at emitOne (events.js:77:13)
  at Socket.emit (events.js:169:7)
  at readableAddChunk (_stream_readable.js:146:16)
  at Socket.Readable.push (_stream_readable.js:110:10)
  at Pipe.onread (net.js:520:20)

```

### Commands

```
     -0:57.2.0 core:select-all (atom-text-editor.editor.is-focused)
     -0:56.4.0 core:copy (atom-text-editor.editor.is-focused)
     -0:55.2.0 window:focus-pane-on-right (atom-text-editor.editor.is-focused)
     -0:54.1.0 core:paste (atom-text-editor.editor.is-focused)
     -0:52.9.0 editor:newline (atom-text-editor.editor.is-focused)
  6x -0:23.8.0 core:move-up (atom-text-editor.editor.is-focused)
     -0:22 core:move-right (atom-text-editor.editor.is-focused)
     -0:21.9.0 core:move-down (atom-text-editor.editor.is-focused)
 73x -0:21.1.0 core:backspace (atom-text-editor.editor.is-focused)
     -0:16.1.0 core:move-down (atom-text-editor.editor.is-focused)
     -0:15.5.0 core:backspace (atom-text-editor.editor.is-focused)
     -0:14.3.0 core:save (atom-text-editor.editor.is-focused)
     -0:13.2.0 core:select-all (atom-text-editor.editor.is-focused)
     -0:11.4.0 core:copy (atom-text-editor.editor.is-focused)
     -0:10.5.0 window:focus-pane-on-right (atom-text-editor.editor.is-focused)
     -0:09.5.0 core:close (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "themes": [
      "one-dark-ui",
      "seti-syntax"
    ]
  },
  "Repl": {}
}
```

### Installed Packages

```coffee
# User
browser-plus, v0.0.34
file-icons, v1.6.9
highlight-selected, v0.10.1
language-latex, v0.6.1
language-ocaml, v1.1.2
latex, v0.25.1
latexer, v0.2.7
linter, v1.5.2
linter-chktex, v1.1.0
linter-pylama, v0.2.0
minimap, v4.13.3
minimap-find-and-replace, v4.3.0
minimap-highlight-selected, v4.3.0
minimap-linter, v1.0.0
pdf-view, v0.23.0
Repl, v0.5.0
script, v2.26.4
seti-syntax, v0.4.0
terminal-status, v1.6.8
tree-view-filter, v0.3.7

# Dev
No dev packages
```

**Comment by mn3mos** [comment]
Hi, would be nice to just catch & ignore the error so that we can close the REPL without the ugly error popup.

Thanks a lot
